@csrf
@if ($method !== 'POST')
    @method($method)
@endif
<div class="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
    <div><x-input-label for="service_type_id" value="Jenis layanan" /><select id="service_type_id" name="service_type_id" class="mt-1 block w-full rounded-md border-gray-300" required><option value="">Pilih layanan</option>@foreach ($serviceTypes as $serviceType)<option value="{{ $serviceType->id }}" @selected((string) old('service_type_id', $servicePrice->service_type_id ?? '') === (string) $serviceType->id)>{{ $serviceType->name }}</option>@endforeach</select><x-input-error :messages="$errors->get('service_type_id')" class="mt-2" /></div>
    <div><x-input-label for="paper_type_id" value="Jenis kertas" /><select id="paper_type_id" name="paper_type_id" class="mt-1 block w-full rounded-md border-gray-300" required><option value="">Pilih kertas</option>@foreach ($paperTypes as $paperType)<option value="{{ $paperType->id }}" @selected((string) old('paper_type_id', $servicePrice->paper_type_id ?? '') === (string) $paperType->id)>{{ $paperType->code }} — {{ $paperType->name }}</option>@endforeach</select><x-input-error :messages="$errors->get('paper_type_id')" class="mt-2" /></div>
    <div><x-input-label for="print_mode_id" value="Mode cetak (opsional)" /><select id="print_mode_id" name="print_mode_id" class="mt-1 block w-full rounded-md border-gray-300"><option value="">Tidak ada</option>@foreach ($printModes as $printMode)<option value="{{ $printMode->id }}" @selected((string) old('print_mode_id', $servicePrice->print_mode_id ?? '') === (string) $printMode->id)>{{ $printMode->name }}</option>@endforeach</select><x-input-error :messages="$errors->get('print_mode_id')" class="mt-2" /></div>
    <div><x-input-label for="side_mode" value="Mode sisi" /><select id="side_mode" name="side_mode" class="mt-1 block w-full rounded-md border-gray-300" required>@foreach ($sideModes as $sideMode)<option value="{{ $sideMode->value }}" @selected(old('side_mode', isset($servicePrice) ? $servicePrice->side_mode->value : 'none') === $sideMode->value)>{{ $sideMode->label() }}</option>@endforeach</select><x-input-error :messages="$errors->get('side_mode')" class="mt-2" /></div>
    <div><x-input-label for="price" value="Harga" /><x-text-input id="price" name="price" type="number" min="0" step="0.01" class="mt-1 block w-full" :value="old('price', $servicePrice->price ?? 0)" required /><x-input-error :messages="$errors->get('price')" class="mt-2" /></div>
    <div><x-input-label for="effective_from" value="Berlaku mulai" /><x-text-input id="effective_from" name="effective_from" type="date" class="mt-1 block w-full" :value="old('effective_from', isset($servicePrice) ? $servicePrice->effective_from->format('Y-m-d') : now()->format('Y-m-d'))" required /><x-input-error :messages="$errors->get('effective_from')" class="mt-2" /></div>
    <div><x-input-label for="effective_until" value="Berlaku sampai (opsional)" /><x-text-input id="effective_until" name="effective_until" type="date" class="mt-1 block w-full" :value="old('effective_until', isset($servicePrice) ? $servicePrice->effective_until?->format('Y-m-d') : '')" /><x-input-error :messages="$errors->get('effective_until')" class="mt-2" /></div>
</div>
<div class="mt-4 rounded-lg bg-blue-50 p-3 text-xs text-blue-800">Fotokopi: pilih mode sisi dan kosongkan mode cetak. Cetak: pilih mode cetak dan gunakan mode sisi “Tidak berlaku”.</div>
<input type="hidden" name="is_active" value="0"><label class="mt-5 inline-flex items-center"><input type="checkbox" name="is_active" value="1" class="rounded border-gray-300 text-blue-700" @checked((bool) old('is_active', $servicePrice->is_active ?? true))><span class="ml-2 text-sm">Tarif aktif</span></label>
<div class="mt-6 flex justify-end gap-3"><a href="{{ route('service-prices.index') }}" class="rounded-lg border px-4 py-2 text-sm">Batal</a><button class="rounded-lg bg-blue-700 px-4 py-2 text-sm font-medium text-white">Simpan</button></div>
