expose_php=Off
display_errors=Off
log_errors=On
memory_limit=256M
upload_max_filesize=20M
post_max_size=20M
max_execution_time=60
date.timezone=Asia/Bangkok

opcache.enable=1
opcache.validate_timestamps=0
opcache.memory_consumption=128
opcache.max_accelerated_files=10000

